import {NAME} from "./constants";

export const GET_HUB_CARDS = `${NAME}/GET_HUB_CARDS`;
export const GET_HOW_TO = `${NAME}/GET_HOW_TO`;
export const TOGGLE_HOW_TO = `${NAME}/TOGGLE_HOW_TO`;
export const DISPLAY_USER_STATS = `${NAME}/DISPLAY_USER_STATS`;
export const COOKIE_BANNER_SEEN = `${NAME}/COOKIE_BANNER_SEEN`;
export const LOG_ACCESS = `${NAME}/LOG_ACCESS`;
export const SETTINGS = `${NAME}/SETTINGS`;

export const USER_IS_SUSPENDED = `${NAME}/USER_IS_SUSPENDED`;
export const USER_IS_LOGGED_OUT = `${NAME}/USER_IS_LOGGED_OUT`;
export const LOG_ACCESS_LOADER = `${NAME}/LOG_ACCESS_LOADER`;
export const GET_USERS_LEVEL_DATA = `${NAME}/GET_USERS_LEVEL_DATA`;
export const GET_GAMES_DATA = `${NAME}/GET_GAMES_DATA`;
export const GAMES_DATA_LOADER = `${NAME}/GAMES_DATA_LOADER`;
export const WEEK_STATS = `${NAME}/WEEK_STATS`;
export const FUN_FACTS = `${NAME}/FUN_FACTS`;
export const TOGGLE_DAILY_REWARD_FIRST_POPUP = `${NAME}/TOGGLE_DAILY_REWARD_FIRST_POPUP`;
export const TOGGLE_DAILY_REWARD_CLAIMED_POPUP = `${NAME}/TOGGLE_DAILY_REWARD_CLAIMED_POPUP`;
export const CLAIM_DAILY_REVEAL = `${NAME}/CLAIM_DAILY_REVEAL`;
export const POLL_VOTE = `${NAME}/POLL_VOTE`;
export const SUBMIT_POLL_VOTE = `${NAME}/SUBMIT_POLL_VOTE`;
export const TOGGLE_DAILY_REWARD_BEFORE_COUNTER_POPUP = `${NAME}/TOGGLE_DAILY_REWARD_BEFORE_COUNTER_POPUP`;





