import {NAME} from "./constants";

export const GET_STORE_ITEMS = `${NAME}/GET_STORE_ITEMS`;
export const GET_INVENTORY_ITEMS = `${NAME}/GET_INVENTORY_ITEMS`;
export const SHOW_INVENTORY_ITEMS = `${NAME}/SHOW_INVENTORY_ITEMS`;
export const ADD_INVENTORY = `${NAME}/ADD_INVENTORY`;
export const OPEN_STORE_ITEM_POPUP = `${NAME}/OPEN_STORE_ITEM_POPUP`;
export const GOTO_INVENTORY = `${NAME}/GOTO_INVENTORY`;
export const GET_KIT_BAGS = `${NAME}/GET_KIT_BAGS`;
export const GET_KIT_BAGS_REWARDS = `${NAME}/GET_KIT_BAGS_REWARDS`;
export const SHOW_KITBAG_ANIMATIONS = `${NAME}/SHOW_KITBAG_ANIMATIONS`;
export const TOGGLE_BOOST_POPUP = `${NAME}/TOGGLE_BOOST_POPUP`;
export const TOGGLE_INVERNTORY_POPUP = `${NAME}/TOGGLE_INVERNTORY_POPUP`;