import {NAME} from "./constants";

export const SUBMIT_USER_DISPLAY_NAME = `${NAME}/SUBMIT_USER_DISPLAY_NAME`;
export const GET_LEADERBOARD_DATA = `${NAME}/GET_LEADERBOARD_DATA`;
export const GET_LEADERBOARD_WEEK_STATS = `${NAME}/GET_LEADERBOARD_WEEK_STATS`;
export const GET_USER_BENEFITS_POPUP_INFO = `${NAME}/GET_USER_BENEFITS_POPUP_INFO`;
export const GET_USER_INVENTORY_POPUP_INFO = `${NAME}/GET_USER_INVENTORY_POPUP_INFO`;
export const GET_USER_POPUP_INFO = `${NAME}/GET_USER_POPUP_INFO`;
export const SHOW_PRIZE_POPUPS = `${NAME}/SHOW_PRIZE_POPUPS`;
export const GET_LEADERBOARD_WEEKS = `${NAME}/GET_LEADERBOARD_WEEKS`;